var header = require('gulp-header');

// using data from package.json for banner
var pkg = require('../package.json');

// Banners added to the tops of all files generated by the tool.
module.exports = {
    html: function() {return header([
      '<!--',
      ' * <%= pkg.banner %>',
      ' * @version v<%= pkg.version %>',
      ' * @link <%= pkg.homepage %>',
      ' * @license <%= pkg.license %>',
      ' *-->',
      ''].join('\n'), {pkg: pkg});
    },
    css: function() {return header([
      '/**',
      ' * <%= pkg.banner %>',
      ' * @version v<%= pkg.version %>',
      ' * @link <%= pkg.homepage %>',
      ' * @license <%= pkg.license %>',
      ' */',
      ''].join('\n'), {pkg: pkg});
    },
    js: function() {return header([
      '/**',
      ' * <%= pkg.banner %>',
      ' * @version v<%= pkg.version %>',
      ' * @version v<%= pkg.version %>',
      ' * @link <%= pkg.homepage %>',
      ' * @license <%= pkg.license %>',
      ' */',
      ''].join('\n'), {pkg: pkg});
    }
}